export const BIDANG = {
  si: 'Sistem Informasi',
  ti: 'Teknik Informatika',
  ar: 'Arsitektur',
  hi: 'Ilmu Politik atau HI',
  km: 'Ilmu Komunikasi',
};

export const STATUS = { buka: 'Lagi dibuka', segera: 'Segera buka', tutup: 'Udah lewat' };
const URUT = { buka: 0, segera: 1, tutup: 2 };

export const PERTANYAAN = [
  {
    k: 'bidang',
    t: 'Jurusan S1 kamu apa?',
    b: 'Ini penyaring yang paling menentukan. Beberapa beasiswa cuma buka bidang tertentu.',
    o: [['si', 'Sistem Informasi'], ['ti', 'Teknik Informatika'], ['ar', 'Arsitektur'], ['hi', 'Ilmu Politik atau HI'], ['km', 'Ilmu Komunikasi']],
  },
  {
    k: 'benua',
    t: 'Mau lanjut ke benua mana?',
    b: 'Pilih terbuka semua kalau belum ada gambaran.',
    o: [['semua', 'Terbuka semua'], ['Asia', 'Asia'], ['Eropa', 'Eropa'], ['Amerika', 'Amerika'], ['Oseania', 'Oseania']],
  },
  {
    k: 'loa',
    t: 'Udah punya surat penerimaan dari kampus tujuan?',
    b: 'Ada yang mensyaratkan di awal, ada juga yang justru mengurus penempatan buat kamu.',
    o: [['abai', 'Belum kepikiran sejauh itu'], ['punya', 'Udah punya'], ['belum', 'Belum, dan pengin dibantu penempatan']],
  },
  {
    k: 'kerja',
    t: 'Udah berapa lama kamu kerja?',
    b: 'Beberapa program menetapkan minimum yang nggak bisa ditawar.',
    o: [['abai', 'Nggak usah disaring'], ['0', 'Belum pernah'], ['2', 'Dua tahun atau lebih']],
  },
  {
    k: 'ikat',
    t: 'Siap terikat pulang ke Indonesia setelah lulus?',
    b: 'Beasiswa pemerintah biasanya minta komitmen ini.',
    o: [['abai', 'Nggak masalah'], ['tolak', 'Lebih suka tanpa ikatan']],
  },
];

export const DEFAULT_JAWABAN = { bidang: '', benua: 'semua', loa: 'abai', kerja: 'abai', ikat: 'abai' };

export const BEASISWA = [
  {
    slug: 'mext-monbukagakusho', k: 'MEXT Monbukagakusho', ng: 'Jepang', b: 'Asia',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 0, kerja: 0, ikat: 0, td: '22 April', st: 'tutup', u: 'id.emb-japan.go.jp',
    intro: 'Seleksinya paling panjang di antara semua beasiswa di sini. Dari daftar sampai berangkat bisa makan waktu setahun penuh, jadi siapkan mental buat nunggu lama.',
    fk: [['Penyelenggara', 'Kemendikbud Jepang'], ['Tunjangan', '¥145.000 sebulan'], ['Jalur', 'Kedutaan atau kampus'], ['Lama seleksi', 'Sekitar setahun']],
    ceklis: [[1, 'Ijazah dan transkrip S1', 'Kertas A4, nggak ada pengecualian'], [1, 'Minat ke bahasa dan budaya Jepang', 'Kelihatan dari esai dan wawancara'], [0, 'Surat rekomendasi', 'Dari dosen atau atasan'], [0, 'Rencana penelitian', 'Ini inti penilaian jalur Research Student'], [0, 'Latihan soal ujian tulis', 'Materinya nyesuaikan bidang yang kamu pilih']],
    waktu: [['April', 'Daftar online, kirim berkas fisik', 0], ['Mei', 'Seleksi berkas', 0], ['Juni', 'Ujian tulis', 0], ['Juli', 'Wawancara', 0], ['Januari', 'Hasil akhir dari Jepang', 0]],
    awas: 'Berkas harus dikirim ke kantor perwakilan yang sesuai alamat KTP kamu. Salah kantor, berkasnya ditolak sebelum sempat dibaca. Ini sering banget kejadian.',
    pcat: 'MEXT nggak mengunci kamu ke daftar prodi tertentu. Kamu yang mencari profesor dan lab yang cocok, lalu mengajukannya sebagai rencana riset.',
    prog: [
      { slug: 'ist-tokyo', n: 'Information Science and Technology', kmp: 'University of Tokyo', bid: 'ti', dur: '2 tahun', bhs: 'Inggris dan Jepang', d: 'Salah satu jurusan komputer paling kuat di Jepang, dengan lab yang tersebar dari machine learning sampai sistem terdistribusi. Untuk jalur Research Student, kamu perlu menghubungi profesor tujuan lebih dulu dan menyusun rencana riset bersama.', p: ['Riset di bawah satu profesor pembimbing, bukan kelas terjadwal seperti S2 pada umumnya', 'Bisa masuk sebagai research student dulu, baru ikut ujian masuk program master', 'Banyak lab menerima diskusi lewat email 6 sampai 12 bulan sebelum tenggat'] },
      { slug: 'cs-titech', n: 'Computer Science', kmp: 'Tokyo Institute of Technology', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Program berbahasa Inggris penuh, jadi kemampuan bahasa Jepang bukan penghalang di awal. Fokusnya lebih ke arah rekayasa perangkat lunak dan sistem cerdas.', p: ['Bahasa pengantar Inggris, kursus Jepang tetap disediakan', 'Jalur University Recommendation sering lebih terbuka di sini ketimbang jalur Kedutaan', 'Punya kerja sama riset dengan industri Jepang'] },
      { slug: 'urban-kyoto', n: 'Urban Engineering dan Architecture', kmp: 'Kyoto University', bid: 'ar', dur: '2 tahun', bhs: 'Inggris dan Jepang', d: 'Menggabungkan arsitektur dengan perencanaan kota. Cocok kalau minat kamu ke arah bangunan tahan gempa, kota padat, atau pelestarian kawasan bersejarah, yang semuanya jadi keahlian khas Jepang.', p: ['Kuat di rekayasa gempa dan perencanaan kawasan padat', 'Riset lapangan jadi bagian besar dari program', 'Ada jalur studi pelestarian bangunan tradisional'] },
      { slug: 'pp-grips', n: 'Public Policy', kmp: 'GRIPS Tokyo', bid: 'hi', dur: '1 sampai 2 tahun', bhs: 'Inggris', d: 'Kampus pascasarjana khusus kebijakan publik, seluruhnya berbahasa Inggris, dan mahasiswanya banyak yang pegawai pemerintah dari berbagai negara. Kelasnya terasa seperti ruang diskusi antarnegara.', p: ['Seluruh program berbahasa Inggris', 'Sesama mahasiswa banyak dari kementerian negara lain', 'Fokus ke kebijakan pembangunan Asia'] },
      { slug: 'media-keio', n: 'Media and Governance', kmp: 'Keio University SFC', bid: 'km', dur: '2 tahun', bhs: 'Inggris dan Jepang', d: 'Program lintas bidang yang menyatukan media, teknologi, dan kebijakan. Kalau latar belakang kamu komunikasi tapi tertarik ke sisi digitalnya, ini pintu masuk yang masuk akal.', p: ['Lintas bidang, bukan ilmu komunikasi murni', 'Banyak proyek berbasis studio dan lapangan', 'Kampus SFC terkenal eksperimental'] },
    ],
  },
  {
    slug: 'global-korea-scholarship', k: 'Global Korea Scholarship', ng: 'Korea Selatan', b: 'Asia',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 0, kerja: 0, ikat: 0, td: '25 Februari', st: 'tutup', u: 'studyinkorea.go.kr',
    intro: 'Kuota Indonesia termasuk yang paling gemuk, 104 orang lewat jalur Kedutaan untuk jenjang pascasarjana. Yang bikin gugur biasanya bukan nilai, tapi urusan berkas.',
    fk: [['Penyelenggara', 'NIIED Korea'], ['Kuota Indonesia', '104 orang'], ['Batas usia', 'Di bawah 40'], ['Bahasa', 'Ada kursus Korea']],
    ceklis: [[1, 'Ijazah S1 atau surat perkiraan lulus', 'Transkrip final paling lambat 31 Juli'], [0, 'Apostille Kemenkumham', 'Makan waktu berminggu-minggu, mulai tiga bulan sebelumnya'], [0, 'Personal Statement dan Study Plan', 'Dua dokumen terpisah'], [0, 'Dua surat rekomendasi', 'Untuk S2 dan S3'], [0, 'Tiga pilihan kampus', 'Minimal satu dari kelompok Type B']],
    waktu: [['Februari', 'Aplikasi dibuka lalu ditutup', 0], ['Maret', 'Seleksi berkas, lanjut wawancara', 0], ['April sampai Mei', 'Seleksi tahap dua oleh NIIED', 0], ['Mei sampai Juni', 'Seleksi oleh kampus', 0], ['Akhir Juni', 'Hasil akhir', 0]],
    awas: 'Tiga pilihan kampus nggak boleh semuanya Type A. Salah susun komposisi ini, aplikasi kamu gugur di meja administrasi padahal profilnya bagus.',
    pcat: 'Kampus dibagi jadi Type A dan Type B. Yang di bawah ini contoh dari keduanya, jadi perhatikan labelnya waktu menyusun tiga pilihan.',
    prog: [
      { slug: 'cs-kaist', n: 'Computer Science', kmp: 'KAIST · Type A', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Kampus teknologi terkuat Korea, sangat dominan di AI, robotika, dan bioteknologi. Juga jadi salah satu kampus favorit awardee LPDP, jadi kamu punya dua jalur pendanaan ke tempat yang sama.', p: ['Seluruh program pascasarjana berbahasa Inggris', 'Termasuk kampus Global Network GKS', 'Persaingan masuk paling ketat di antara kampus GKS'] },
      { slug: 'pp-kdi', n: 'Public Policy', kmp: 'KDI School · Type A', bid: 'hi', dur: '1 sampai 2 tahun', bhs: 'Inggris', d: 'Sekolah pascasarjana khusus kebijakan publik dan manajemen pembangunan. Mahasiswanya banyak birokrat dari negara berkembang, jadi diskusinya berangkat dari masalah nyata di lapangan.', p: ['Masuk daftar Global Network GKS', 'Berbahasa Inggris penuh', 'Kuat di kebijakan pembangunan dan ekonomi'] },
      { slug: 'arch-hongik', n: 'Architecture', kmp: 'Hongik University · Type A', bid: 'ar', dur: '2 tahun', bhs: 'Korea dan Inggris', d: 'Hongik dikenal sebagai kampus seni dan desain paling kuat di Korea. Program arsitekturnya bersentuhan langsung dengan jurusan desain lain di kampus yang sama.', p: ['Reputasi kuat di seni, desain, dan arsitektur', 'Sebagian mata kuliah berbahasa Korea', 'Lokasinya di Seoul'] },
      { slug: 'is-pusan', n: 'Information Systems', kmp: 'Pusan National University · Type B', bid: 'si', dur: '2 tahun', bhs: 'Korea dan Inggris', d: 'Kampus negeri besar di Busan. Karena masuk Type B, mendaftar ke sini membantu kamu memenuhi aturan komposisi tiga pilihan kampus.', p: ['Type B, jadi aman untuk aturan komposisi', 'Biaya hidup Busan lebih rendah dari Seoul', 'Termasuk daftar Global Network GKS'] },
      { slug: 'media-yonsei', n: 'Media and Communication', kmp: 'Yonsei University · Type A', bid: 'km', dur: '2 tahun', bhs: 'Inggris', d: 'Salah satu dari tiga kampus paling bergengsi di Korea. Program media dan komunikasinya banyak menyentuh industri budaya populer Korea yang sedang jadi perhatian dunia.', p: ['Termasuk kampus Global Network GKS', 'Dekat dengan industri media Seoul', 'Persaingan tinggi karena banyak peminat'] },
    ],
  },
  {
    slug: 'turkiye-burslari', k: 'Turkiye Burslari', ng: 'Turki', b: 'Asia',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 0, kerja: 0, ikat: 0, td: '20 Februari', st: 'tutup', u: 'turkiyeburslari.gov.tr',
    intro: 'Satu-satunya beasiswa besar yang mengurus penempatan kampus dan jurusan buat kamu. Jadi nggak perlu berburu surat penerimaan dulu, tapi kamu juga nggak sepenuhnya memilih.',
    fk: [['Penyelenggara', 'YTB Turki'], ['Pelamar setahun', '165.000 lebih'], ['Yang diterima', 'Sekitar 5.000'], ['Bahasa', 'Kursus Turki setahun']],
    ceklis: [[1, 'Ijazah dan transkrip', 'Terjemahan resmi kalau bukan bahasa Inggris'], [0, 'Paspor atau KTP', ''], [0, 'Esai motivasi', 'Kenapa Turki, bukan negara lain'], [0, 'Surat rekomendasi', ''], [0, 'Susun urutan preferensi kampus', 'Panitia yang menentukan hasil akhirnya']],
    waktu: [['10 Januari', 'Pendaftaran dibuka', 0], ['20 Februari', 'Pendaftaran ditutup', 0], ['Maret sampai Mei', 'Seleksi berkas', 0], ['Juni sampai Juli', 'Wawancara', 0], ['Agustus', 'Pengumuman penempatan', 0]],
    awas: 'Kamu mengajukan preferensi, bukan mendaftar langsung ke kampus. Panitia yang menentukan kamu masuk mana, jadi susun urutan preferensinya serealistis mungkin.',
    pcat: 'Kamu memilih preferensi, bukan mendaftar ke kampus. Ini beberapa kampus yang paling sering jadi tujuan pelamar Indonesia.',
    prog: [
      { slug: 'ce-metu', n: 'Computer Engineering', kmp: 'Middle East Technical University', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'METU adalah kampus teknik paling dihormati di Turki dan seluruh pengajarannya berbahasa Inggris. Jadi tujuan utama banyak pelamar Turkiye Burslari dari jalur teknik.', p: ['Seluruh program berbahasa Inggris', 'Kampus teknik peringkat teratas di Turki', 'Lokasinya di Ankara'] },
      { slug: 'arch-itu', n: 'Architecture', kmp: 'Istanbul Technical University', bid: 'ar', dur: '2 tahun', bhs: 'Inggris dan Turki', d: 'Berada di kota yang jadi ruang kelas raksasa untuk arsitektur, dari peninggalan Bizantium sampai Ottoman. Programnya banyak menyentuh pelestarian dan adaptasi bangunan lama.', p: ['Konteks kota yang kaya untuk studi arsitektur', 'Kuat di konservasi dan restorasi', 'Sebagian kelas berbahasa Turki'] },
      { slug: 'ir-bilkent', n: 'International Relations', kmp: 'Bilkent University', bid: 'hi', dur: '2 tahun', bhs: 'Inggris', d: 'Turki duduk persis di persimpangan Eropa, Timur Tengah, dan Asia Tengah. Program HI di sini membahas kawasan yang jarang jadi fokus kampus Barat.', p: ['Fokus ke kawasan Timur Tengah dan Asia Tengah', 'Seluruhnya berbahasa Inggris', 'Kampus swasta dengan reputasi riset kuat'] },
      { slug: 'media-ankara', n: 'Media and Communication', kmp: 'Ankara University', bid: 'km', dur: '2 tahun', bhs: 'Turki', d: 'Fakultas komunikasi tertua di Turki. Pengantarnya bahasa Turki, jadi tahun kursus bahasa yang disediakan program jadi krusial di sini.', p: ['Fakultas komunikasi tertua di Turki', 'Pengantar bahasa Turki', 'Kursus bahasa setahun jadi syarat wajib'] },
    ],
  },
  {
    slug: 'csc-china', k: 'Chinese Government Scholarship', ng: 'China', b: 'Asia',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 0, kerja: 0, ikat: 0, td: '30 April', st: 'tutup', u: 'campuschina.org',
    intro: 'Kuotanya jauh lebih besar dibanding beasiswa papan atas lain, jadi secara hitungan peluangnya lebih terbuka. Tantangannya justru di tenggat yang berantakan antar kampus.',
    fk: [['Penyelenggara', 'China Scholarship Council'], ['Tunjangan', 'CNY 3.000 sampai 3.500'], ['Tempat tinggal', 'Asrama kampus'], ['Bahasa', 'Inggris atau Mandarin']],
    ceklis: [[1, 'Ijazah dan transkrip S1', ''], [0, 'IELTS, TOEFL, atau HSK', 'Tergantung bahasa pengantar programnya'], [0, 'Rencana studi', ''], [0, 'Dua surat rekomendasi', ''], [0, 'Cek tenggat internal kampus', 'Biasanya jauh lebih awal']],
    waktu: [['Desember', 'Portal umum dibuka', 0], ['Januari sampai Maret', 'Tenggat internal tiap kampus', 0], ['30 April', 'Batas akhir jendela umum', 0], ['Juni sampai Juli', 'Pengumuman bertahap', 0]],
    awas: 'Tanggal 30 April itu batas jendela umum, bukan tenggat kamu. Banyak kampus tutup pendaftaran jauh lebih awal, jadi yang berlaku adalah tanggal kampus tujuan.',
    pcat: 'CSC berlaku di ratusan kampus. Ini beberapa yang punya program berbahasa Inggris dan sering menerima mahasiswa Indonesia.',
    prog: [
      { slug: 'cs-tsinghua', n: 'Computer Science and Technology', kmp: 'Tsinghua University', bid: 'ti', dur: '2 sampai 3 tahun', bhs: 'Inggris', d: 'Kampus teknik nomor satu di China dan salah satu yang teratas di dunia. Juga masuk daftar kampus kemitraan LPDP, jadi ada lebih dari satu cara ke sini.', p: ['Peringkat teratas dunia untuk ilmu komputer', 'Masuk daftar kemitraan LPDP', 'Persaingan sangat ketat'] },
      { slug: 'arch-tongji', n: 'Architecture', kmp: 'Tongji University', bid: 'ar', dur: '2 sampai 3 tahun', bhs: 'Inggris', d: 'Sekolah arsitektur paling dikenal di China, berada di Shanghai. Programnya banyak bersinggungan dengan urbanisasi cepat yang sedang terjadi di sekelilingnya.', p: ['Sekolah arsitektur terkemuka di China', 'Studi kota jadi bagian besar kurikulum', 'Ada jalur berbahasa Inggris'] },
      { slug: 'ir-peking', n: 'International Relations', kmp: 'Peking University', bid: 'hi', dur: '2 sampai 3 tahun', bhs: 'Inggris dan Mandarin', d: 'Kalau kamu ingin memahami cara China memandang dunia, mempelajarinya dari dalam memberi sudut pandang yang sulit didapat di tempat lain.', p: ['Sudut pandang China atas politik global', 'Sebagian program berbahasa Inggris', 'Sekolah Yenching punya jalur pendanaan terpisah'] },
      { slug: 'jurnalisme-fudan', n: 'Journalism and Communication', kmp: 'Fudan University', bid: 'km', dur: '2 sampai 3 tahun', bhs: 'Inggris dan Mandarin', d: 'Fakultas jurnalisme tertua di China, berada di Shanghai. Menariknya justru pada bagaimana lanskap media yang sangat berbeda dipelajari secara akademik.', p: ['Fakultas jurnalisme tertua di China', 'Ada jalur berbahasa Inggris', 'Lokasi di pusat media Shanghai'] },
    ],
  },
  {
    slug: 'schwarzman-scholars', k: 'Schwarzman Scholars', ng: 'China', b: 'Asia',
    bid: ['hi'], loa: 0, kerja: 0, ikat: 0, td: 'September', st: 'segera', u: 'schwarzmanscholars.org',
    intro: 'Program setahun di Tsinghua yang menyaring berdasarkan potensi kepemimpinan, bukan seberapa tinggi IPK kamu.',
    fk: [['Gelar', 'Master of Global Affairs'], ['Durasi', 'Satu tahun'], ['Lokasi', 'Beijing'], ['Pendanaan', 'Penuh']],
    ceklis: [[1, 'Ijazah S1', ''], [0, 'Esai kepemimpinan', 'Bagian yang paling menentukan'], [0, 'Surat rekomendasi', ''], [0, 'Rencana capstone project', 'Syarat kelulusan'], [0, 'Latihan wawancara panel', '']],
    waktu: [['September', 'Pendaftaran ditutup', 1], ['Oktober', 'Seleksi berkas', 0], ['November', 'Wawancara panel', 0], ['Desember', 'Pengumuman', 0]],
    awas: 'Program ini praktis tertutup untuk teknik murni. Kalau latar belakang kamu Sistem Informasi atau Teknik Informatika, kamu harus bisa menunjukkan sisi kebijakan dari pekerjaanmu.',
    pcat: 'Cuma ada satu program, dan semua penerima mengambil jalur yang sama.',
    prog: [
      { slug: 'mga-tsinghua', n: 'Master of Global Affairs', kmp: 'Tsinghua University', bid: 'hi', dur: '1 tahun', bhs: 'Inggris', d: 'Satu-satunya program dalam beasiswa ini. Kurikulumnya menggabungkan kelas akademik dengan kunjungan lapangan ke lembaga dan perusahaan di seluruh China, ditutup dengan capstone project.', p: ['Tiga pilar: kepemimpinan, ekonomi dan bisnis, hubungan internasional', 'Wajib menyelesaikan capstone project', 'Tinggal satu tahun penuh di kampus Tsinghua', 'Bergabung ke jaringan alumni global setelah lulus'] },
    ],
  },
  {
    slug: 'adb-scholarship', k: 'ADB Scholarship', ng: 'Asia Pasifik', b: 'Asia',
    bid: ['hi'], loa: 0, kerja: 2, ikat: 0, td: 'Bervariasi', st: 'segera', u: 'adb.org',
    intro: 'Diselenggarakan Asian Development Bank bareng kampus mitra di kawasan Asia Pasifik. Khusus buat yang kerja di bidang pembangunan.',
    fk: [['Penyelenggara', 'Asian Development Bank'], ['Bidang', 'Ekonomi dan kebijakan'], ['Bahasa', 'IELTS 6.0 sampai 6.5'], ['Pendanaan', 'Penuh']],
    ceklis: [[1, 'Pengalaman kerja relevan', 'Umumnya minimal dua tahun'], [0, 'Ijazah dan transkrip', ''], [0, 'IELTS atau TOEFL', 'Ambangnya beda tiap kampus mitra'], [0, 'Surat rekomendasi', ''], [0, 'Pilih kampus mitra dulu', 'Daftarnya lewat kampus, bukan lewat ADB']],
    waktu: [['Bervariasi', 'Ikut kalender masing-masing kampus mitra', 0]],
    awas: 'Kamu nggak melamar ke ADB. Pendaftarannya lewat kampus mitra, dan tiap kampus punya tenggat serta syarat bahasa yang beda.',
    pcat: 'Semua pendaftaran lewat kampus mitra. Ini beberapa yang menerima pelamar Indonesia.',
    prog: [
      { slug: 'pp-nus', n: 'Public Policy', kmp: 'National University of Singapore', bid: 'hi', dur: '2 tahun', bhs: 'Inggris', d: 'Lee Kuan Yew School of Public Policy jadi salah satu tujuan paling diminati. Dekat secara geografis dan kurikulumnya banyak membahas kasus Asia Tenggara.', p: ['Fokus ke kebijakan publik Asia', 'Juga masuk daftar kemitraan LPDP', 'Dekat dari Indonesia'] },
      { slug: 'dev-econ-tokyo', n: 'Development Economics', kmp: 'University of Tokyo', bid: 'hi', dur: '2 tahun', bhs: 'Inggris', d: 'Program ekonomi pembangunan dengan sumber pendanaan dari Japan Scholarship Program. Cocok untuk yang bekerja di lembaga perencanaan atau kementerian.', p: ['Didukung Japan Scholarship Program', 'Berbahasa Inggris', 'Kuat di ekonomi pembangunan Asia'] },
      { slug: 'pm-ait', n: 'Public Management', kmp: 'Asian Institute of Technology', bid: 'hi', dur: '2 tahun', bhs: 'Inggris', d: 'Kampus pascasarjana internasional di Thailand yang seluruh mahasiswanya dari berbagai negara Asia. Suasananya sangat multikultural.', p: ['Kampus internasional di Bangkok', 'Biaya hidup relatif terjangkau', 'Banyak mahasiswa dari negara berkembang Asia'] },
    ],
  },
  {
    slug: 'kaust-kfupm', k: 'KAUST dan KFUPM', ng: 'Arab Saudi', b: 'Asia',
    bid: ['si', 'ti'], loa: 0, kerja: 0, ikat: 0, td: '10 Januari', st: 'tutup', u: 'kaust.edu.sa',
    intro: 'Dua kampus riset Arab Saudi yang mendanai penuh semua mahasiswa pascasarjananya. Khusus STEM, jadi bidang sosial nggak dilayani sama sekali.',
    fk: [['Fokus', 'STEM dan riset'], ['Tempat tinggal', 'Asrama gratis'], ['Tiket', 'Pulang tiap libur panas'], ['Bahasa', 'TOEFL iBT 79']],
    ceklis: [[1, 'Latar belakang STEM', 'Di luar itu nggak dilayani'], [0, 'Ijazah dan transkrip', ''], [0, 'TOEFL atau IELTS', ''], [0, 'Statement of purpose', ''], [0, 'Surat rekomendasi', '']],
    waktu: [['10 Januari', 'Tenggat KFUPM siklus 2026', 0], ['Bervariasi', 'KAUST menerima beberapa gelombang', 0]],
    awas: 'KFUPM punya jalur direct entry dari S1 langsung ke S3. Kalau target jangka panjang kamu doktoral, jalur ini memotong satu siklus pendaftaran penuh.',
    pcat: 'Semua program berbahasa Inggris dan berorientasi riset.',
    prog: [
      { slug: 'cs-kaust', n: 'Computer Science', kmp: 'KAUST', bid: 'ti', dur: '1,5 sampai 2 tahun', bhs: 'Inggris', d: 'Kampus riset yang dibangun dari nol dengan dana sangat besar, punya salah satu superkomputer tercepat di dunia. Rasio dosen ke mahasiswa sangat kecil, jadi bimbingan terasa personal.', p: ['Akses ke superkomputer Shaheen', 'Semua mahasiswa didanai penuh tanpa kecuali', 'Kampus berdiri sendiri di tepi Laut Merah'] },
      { slug: 'ce-kfupm', n: 'Computer Engineering', kmp: 'KFUPM', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Kampus teknik tertua dan paling mapan di Arab Saudi, dengan kaitan erat ke industri energi. Punya jalur langsung dari S1 ke S3 yang jarang ditawarkan kampus lain.', p: ['Ada jalur direct entry S1 ke S3', 'Kaitan kuat dengan industri energi', 'Asrama dan tiket pulang tiap musim panas'] },
      { slug: 'ics-kfupm', n: 'Information and Computer Science', kmp: 'KFUPM', bid: 'si', dur: '2 tahun', bhs: 'Inggris', d: 'Lebih dekat ke sisi sistem informasi ketimbang teknik komputer murni. Cocok kalau latar belakang S1 kamu Sistem Informasi.', p: ['Lebih dekat ke sistem informasi daripada teknik keras', 'Berbahasa Inggris penuh', 'Biaya buku ditanggung'] },
    ],
  },
  {
    slug: 'chevening', k: 'Chevening', ng: 'Inggris', b: 'Eropa',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 1, kerja: 2, ikat: 1, td: '7 Oktober', st: 'buka', u: 'chevening.org',
    intro: 'Beasiswa pemerintah Inggris yang membebaskan kamu memilih kampus mana pun, termasuk Oxford, Cambridge, dan LSE. Syaratnya dua tahun pengalaman kerja, dan itu nggak bisa ditawar.',
    fk: [['Penyelenggara', 'FCDO Inggris'], ['Jenjang', 'S2 satu tahun'], ['Kerja', 'Minimal dua tahun'], ['Ikatan', 'Pulang dua tahun']],
    ceklis: [[1, 'Ijazah S1 setara second class upper', 'IPK sekitar 3,00 ke atas'], [1, 'Pengalaman kerja dua tahun', 'Sukarela, paruh waktu, dan magang ikut dihitung'], [0, 'IELTS minimal 6,5', 'Ikut syarat kampus tujuan'], [0, 'Tiga pilihan program master', 'Wajib lewat course finder resmi'], [0, 'Satu unconditional offer', 'Tenggatnya terpisah dari tenggat beasiswa']],
    waktu: [['Agustus', 'Pendaftaran beasiswa dibuka', 1], ['7 Oktober', 'Tenggat aplikasi beasiswa', 0], ['Maret sampai April', 'Wawancara', 0], ['Pertengahan Juni', 'Hasil akhir', 0], ['Awal Juli', 'Tenggat unconditional offer', 0]],
    awas: 'Kamu boleh daftar beasiswa sebelum punya surat penerimaan. Tapi kalau sampai Juli belum ada satu pun kampus yang menerima tanpa syarat, beasiswa yang sudah kamu menangkan tetap hangus.',
    pcat: 'Chevening berlaku di hampir semua kampus Inggris, jadi daftar ini cuma contoh. Pilihan resminya dicari lewat course finder mereka.',
    prog: [
      { slug: 'ipe-lse', n: 'MSc International Political Economy', kmp: 'London School of Economics', bid: 'hi', dur: '1 tahun', bhs: 'Inggris', d: 'LSE adalah rujukan utama untuk ilmu sosial di Inggris. Program ini menyoroti titik temu antara politik dan ekonomi global, yang relevan kalau kamu bekerja di kebijakan perdagangan atau pembangunan.', p: ['Salah satu program IPE paling dikenal di dunia', 'Lokasi di pusat London', 'Persaingan masuk sangat ketat'] },
      { slug: 'global-affairs-kcl', n: 'MSc Global Affairs', kmp: "King's College London", bid: 'hi', dur: '1 tahun', bhs: 'Inggris', d: 'Membahas politik, masyarakat, ekonomi, dan sejarah sebagai satu kesatuan, bukan bidang terpisah. Bagus buat yang ingin gambaran luas ketimbang spesialisasi sempit.', p: ['Pendekatan lintas bidang', 'Fleksibel dalam memilih mata kuliah', 'Kampus di pusat London'] },
      { slug: 'cs-manchester', n: 'MSc Computer Science', kmp: 'University of Manchester', bid: 'ti', dur: '1 tahun', bhs: 'Inggris', d: 'Manchester punya sejarah panjang di komputasi, tempat komputer program tersimpan pertama di dunia dibuat. Programnya juga tersedia lewat jalur GREAT Scholarship.', p: ['Juga masuk daftar kampus GREAT Scholarship', 'Sejarah panjang di bidang komputasi', 'Biaya hidup lebih murah dari London'] },
      { slug: 'ism-leeds', n: 'MSc Information Systems Management', kmp: 'University of Leeds', bid: 'si', dur: '1 tahun', bhs: 'Inggris', d: 'Lebih menyorot sisi manajemen dan tata kelola sistem informasi ketimbang pemrogramannya. Cocok kalau kamu mengarah ke peran analis bisnis atau transformasi digital.', p: ['Fokus ke strategi dan tata kelola, bukan coding', 'Cocok untuk jalur analis bisnis', 'Kelas banyak diisi profesional'] },
      { slug: 'arch-sheffield', n: 'MA Architecture and Urban Design', kmp: 'University of Sheffield', bid: 'ar', dur: '1 tahun', bhs: 'Inggris', d: 'Sekolah arsitektur Sheffield dikenal kuat di arsitektur berbasis kepentingan publik. Banyak proyek studionya berangkat dari masalah kota yang nyata.', p: ['Kuat di arsitektur untuk kepentingan publik', 'Banyak proyek studio berbasis kota nyata', 'Biaya hidup terjangkau'] },
      { slug: 'media-goldsmiths', n: 'MA Media and Communications', kmp: 'Goldsmiths University of London', bid: 'km', dur: '1 tahun', bhs: 'Inggris', d: 'Goldsmiths dikenal karena pendekatan kritis dan eksperimentalnya terhadap media. Cocok kalau kamu ingin membedah media, bukan sekadar mempelajari cara memproduksinya.', p: ['Pendekatan kritis terhadap media', 'Lingkungan kampus yang eksperimental', 'Kuat di studi budaya'] },
    ],
  },
  {
    slug: 'great-scholarship', k: 'GREAT Scholarship', ng: 'Inggris', b: 'Eropa',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 1, kerja: 0, ikat: 0, td: 'April sampai Juni', st: 'segera', u: 'britishcouncil.org',
    intro: 'Jauh lebih ringkas dari Chevening dan nggak minta pengalaman kerja. Tapi cuma berlaku di sekelompok kampus mitra yang daftarnya ganti tiap tahun.',
    fk: [['Penyelenggara', 'British Council'], ['Kampus mitra', 'Sekitar 10 sampai 15'], ['Jenjang', 'Taught master 1 tahun'], ['Bahasa', 'IELTS 6.5 sampai 7.0']],
    ceklis: [[1, 'Paspor Indonesia', ''], [0, 'Surat penerimaan kampus mitra', 'Wajib ada sebelum daftar beasiswa'], [0, 'Cek daftar kampus tahun ini', 'Berubah tiap tahun'], [0, 'IELTS sesuai syarat kampus', ''], [0, 'Esai motivasi', 'Formatnya ditentukan masing-masing kampus']],
    waktu: [['Januari sampai Maret', 'Melamar ke kampus mitra', 0], ['April sampai Juni', 'Tenggat beasiswa, beda tiap kampus', 0], ['Juli', 'Pengumuman', 0], ['September', 'Berangkat', 0]],
    awas: 'Daftar kampus mitra ganti tiap tahun. Jangan menyusun rencana pakai daftar tahun lalu, karena kampus incaran kamu bisa saja sudah keluar dari program.',
    pcat: 'Ini kampus yang pernah masuk daftar mitra. Cek ulang daftar tahun berjalan di situs British Council.',
    prog: [
      { slug: 'cs-york', n: 'MSc Computer Science', kmp: 'University of York', bid: 'ti', dur: '1 tahun', bhs: 'Inggris', d: 'York menyediakan jalur konversi untuk yang latar belakang S1-nya bukan ilmu komputer, jadi pintu masuknya lebih longgar dibanding kampus lain.', p: ['Ada jalur konversi untuk lulusan non-komputer', 'Kota kecil dengan biaya hidup rendah', 'Sering masuk daftar mitra GREAT'] },
      { slug: 'ds-southampton', n: 'MSc Data Science', kmp: 'University of Southampton', bid: 'si', dur: '1 tahun', bhs: 'Inggris', d: 'Southampton kuat di ilmu data dan web science. Programnya menyeimbangkan sisi teknis dengan penerapan di dunia kerja.', p: ['Kuat di web science dan data', 'Seimbang antara teori dan praktik', 'Sering masuk daftar mitra GREAT'] },
      { slug: 'ir-keele', n: 'MA International Relations', kmp: 'University of Keele', bid: 'hi', dur: '1 tahun', bhs: 'Inggris', d: 'Kampus yang konsisten muncul di daftar mitra GREAT. Program HI-nya banyak menyorot isu keadilan global dan hak asasi.', p: ['Langganan daftar mitra GREAT', 'Fokus ke keadilan global dan HAM', 'Kampus dengan suasana tenang'] },
    ],
  },
  {
    slug: 'erasmus-mundus', k: 'Erasmus Mundus', ng: 'Multi negara Eropa', b: 'Eropa',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 0, kerja: 0, ikat: 0, td: 'Oktober sampai Januari', st: 'segera', u: 'erasmus-plus.ec.europa.eu',
    intro: 'Ini bukan satu beasiswa, tapi lebih dari 350 program terpisah yang dikelola konsorsium kampus berbeda-beda. Kamu kuliah berpindah negara selama masa studi.',
    fk: [['Penyelenggara', 'Uni Eropa'], ['Jumlah program', '350 lebih'], ['Durasi', '12 sampai 24 bulan'], ['Negara', 'Minimal dua per program']],
    ceklis: [[1, 'Ijazah S1 atau lagi semester akhir', ''], [0, 'Pilih tiga program berbeda', 'Strategi yang paling sering disarankan alumni'], [0, 'Cek syarat tiap konsorsium', 'Beda total antar program'], [0, 'Motivation letter per program', 'Nggak bisa disalin begitu saja'], [0, 'Catat tenggat masing-masing', 'Ada yang Desember, ada yang Januari']],
    waktu: [['Oktober sampai Desember', 'Sebagian besar program dibuka', 0], ['Desember sampai Februari', 'Rentang tenggat, beda tiap konsorsium', 0], ['Maret sampai Mei', 'Seleksi', 0], ['September', 'Kuliah dimulai', 0]],
    awas: 'Daftar ke satu program Erasmus Mundus nggak sama dengan daftar Erasmus Mundus. Tiap konsorsium menyeleksi sendiri, jadi peluang kamu naik kalau melamar ke beberapa program sekaligus.',
    pcat: 'Ini program yang paling nyambung dengan lima jurusan kita. Katalog lengkapnya ada di situs Erasmus Plus.',
    prog: [
      { slug: 'ediss', n: 'EDISS · Engineering of Data-intensive Intelligent Software Systems', kmp: 'Konsorsium empat kampus Eropa', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Membekali kamu merancang dan mengelola sistem perangkat lunak cerdas berskala besar. Kamu pindah kampus tiap semester atau tahun, tergantung jalur yang dipilih.', p: ['Fokus ke sistem perangkat lunak skala besar', 'Berpindah antar kampus selama masa studi', 'Dapat gelar bersama dari konsorsium'] },
      { slug: 'emai', n: 'EMAI · Artificial Intelligence', kmp: 'Dikoordinasi Pompeu Fabra University', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Program AI dua tahun yang menyeimbangkan teori dan praktik. Dikoordinasi dari Barcelona, dengan kampus mitra tersebar di beberapa negara Eropa.', p: ['Kerangka lengkap teori dan praktik AI', 'Koordinator di Barcelona', 'Didanai Komisi Eropa'] },
      { slug: 'cybersure', n: 'CYBERSURE · Cybersecurity and Assurance', kmp: 'Konsorsium multi negara', bid: 'si', dur: '2 tahun', bhs: 'Inggris', d: 'Program keamanan siber yang menyorot manajemen risiko digital, bukan cuma sisi teknisnya. Relevan buat yang mengarah ke tata kelola keamanan informasi.', p: ['Menggabungkan sisi teknis dan manajemen risiko', 'Program baru yang didanai ulang di katalog 2026', 'Berpindah antar negara'] },
      { slug: 'terra', n: 'TERRA · Earthen Architecture and Construction', kmp: 'Konsorsium arsitektur Eropa', bid: 'ar', dur: '2 tahun', bhs: 'Inggris', d: 'Program arsitektur yang berfokus pada konstruksi berbahan tanah dan material lokal. Sangat relevan untuk konteks Indonesia yang punya tradisi bangunan serupa.', p: ['Fokus ke material tanah dan konstruksi lokal', 'Relevan dengan konteks arsitektur tropis', 'Banyak praktik lapangan'] },
      { slug: 'resco', n: 'RESCO · Arsitektur dan Energi Terbarukan', kmp: 'Dikoordinasi Universite Le Havre', bid: 'ar', dur: '2 tahun', bhs: 'Inggris', d: 'Menyatukan arsitektur, konstruksi, dan energi terbarukan untuk pembangunan kota berkelanjutan. Cocok kalau minat kamu ada di persimpangan bangunan dan iklim.', p: ['Menggabungkan arsitektur dengan energi terbarukan', 'Fokus pembangunan urban berkelanjutan', 'Program baru di katalog 2026'] },
      { slug: 'eps', n: 'EPS · European Politics and Society', kmp: 'Konsorsium kampus Eropa', bid: 'hi', dur: '2 tahun', bhs: 'Inggris', d: 'Membahas integrasi Eropa, sistem politik, dan perubahan sosial di dalamnya. Menarik kalau kamu ingin memahami Uni Eropa sebagai model kerja sama kawasan.', p: ['Fokus ke integrasi dan politik Eropa', 'Berpindah antar kampus di beberapa negara', 'Relevan untuk studi kerja sama kawasan'] },
      { slug: 'lct', n: 'LCT · Language and Communication Technologies', kmp: 'Saarland, Trento, Malta, Lorraine, Charles', bid: 'km', dur: '2 tahun', bhs: 'Inggris', d: 'Titik temu antara linguistik, komunikasi, dan teknologi bahasa. Kalau latar belakang kamu komunikasi tapi tertarik ke sisi komputasinya, ini jembatannya.', p: ['Menggabungkan linguistik dan teknologi', 'Konsorsium lima kampus', 'Membuka jalur ke bidang NLP'] },
      { slug: 'docnomads', n: 'DOCNOMADS PLUS · Documentary Film Directing', kmp: 'Konsorsium film Eropa', bid: 'km', dur: '2 tahun', bhs: 'Inggris', d: 'Program penyutradaraan film dokumenter yang menekankan penceritaan dan sudut pandang budaya. Berpindah antar negara sambil memproduksi karya.', p: ['Berbasis praktik produksi film', 'Berpindah antar negara tiap semester', 'Fokus ke dokumenter dan penceritaan'] },
    ],
  },
  {
    slug: 'stipendium-hungaricum', k: 'Stipendium Hungaricum', ng: 'Hungaria', b: 'Eropa',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 0, kerja: 0, ikat: 0, td: '15 Januari', st: 'tutup', u: 'stipendiumhungaricum.hu',
    intro: 'Salah satu program pemerintah terbesar di Eropa, sekitar 5.200 beasiswa setahun. Biaya hidup Hungaria jauh di bawah Eropa Barat, jadi tunjangannya terasa lebih longgar.',
    fk: [['Penyelenggara', 'Pemerintah Hungaria'], ['Beasiswa setahun', 'Sekitar 5.200'], ['Program', '900 lebih berbahasa Inggris'], ['Bahasa', 'IELTS 5.5 sampai 6.0']],
    ceklis: [[1, 'Ijazah dan transkrip', 'Terjemahan resmi kalau perlu'], [0, 'Hubungi sending partner Indonesia', 'Pra seleksi sering November atau Desember'], [0, 'Sertifikat bahasa', ''], [0, 'Sertifikat medis', 'Wajib pakai template resmi program'], [0, 'Cek bidang yang dibuka untuk Indonesia', 'Ditentukan perjanjian bilateral']],
    waktu: [['November sampai Desember', 'Pra seleksi sending partner', 0], ['15 Januari', 'Tenggat aplikasi', 0], ['Februari sampai Mei', 'Seleksi dan ujian masuk kampus', 0], ['Juni', 'Hasil akhir', 0]],
    awas: 'Bidang studi yang tersedia untuk pelamar Indonesia belum tentu sama dengan negara lain, karena ditentukan lewat perjanjian bilateral. Cek daftar khusus Indonesia sebelum menyusun pilihan.',
    pcat: 'Ada lebih dari 900 program di 30 kampus. Ini beberapa yang paling nyambung dengan lima jurusan kita.',
    prog: [
      { slug: 'cs-elte', n: 'MSc Computer Science', kmp: 'Eotvos Lorand University, Budapest', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Punya empat spesialisasi: Software and Service Architectures, Cybersecurity, Financial Technology, dan Artificial Intelligence. Kampusnya menegaskan program ini berat, dan pelamar tanpa dasar matematika serta pemrograman yang kuat akan kesulitan.', p: ['Empat spesialisasi, semuanya di Budapest', 'Menuntut dasar matematika dan pemrograman yang solid', 'Banyak peluang riset lintas kampus Eropa', 'Kampus sendiri mengingatkan program ini nggak cocok untuk semua orang'] },
      { slug: 'cse-ppke', n: 'MSc Computer Science Engineering', kmp: 'Pazmany Peter Catholic University', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Pendekatannya lebih ke sisi perangkat keras, dengan spesialisasi Software Engineering dan High-Performance Computational Tools. Menyentuh juga bidang info-bionics dan pemrosesan citra.', p: ['Pendekatan berbasis perangkat keras', 'Ada lab riset eksperimental', 'Bisa ikut riset sejak semester awal'] },
      { slug: 'cs-pecs', n: 'BSc Computer Science', kmp: 'University of Pecs', bid: 'ti', dur: '3 tahun', bhs: 'Inggris', d: 'Ini jenjang sarjana, jadi relevan kalau kamu atau adikmu masih di tahap itu. Ada dua peminatan, Software Development dan Geoinformatics, dipilih setelah mengumpulkan 90 kredit.', p: ['Jenjang sarjana, bukan magister', 'Dua peminatan: Software Development dan Geoinformatics', 'Minimal 18 kredit tiap semester'] },
      { slug: 'arch-bme', n: 'MSc Architecture', kmp: 'Budapest University of Technology', bid: 'ar', dur: '2 tahun', bhs: 'Inggris', d: 'Budapest adalah kota dengan warisan arsitektur yang sangat kaya, dari Art Nouveau sampai Brutalisme era sosialis. Programnya banyak bersinggungan dengan konteks itu.', p: ['Konteks kota dengan warisan arsitektur kaya', 'Program berbahasa Inggris', 'Kampus teknik utama Hungaria'] },
      { slug: 'ir-corvinus', n: 'MA International Relations', kmp: 'Corvinus University of Budapest', bid: 'hi', dur: '2 tahun', bhs: 'Inggris', d: 'Menawarkan sudut pandang Eropa Tengah yang jarang terwakili di kampus Eropa Barat. Berguna kalau kamu tertarik pada dinamika negara menengah di dalam Uni Eropa.', p: ['Sudut pandang Eropa Tengah', 'Kampus ekonomi dan sosial utama Hungaria', 'Berbahasa Inggris'] },
      { slug: 'media-szeged', n: 'MA Communication and Media Studies', kmp: 'University of Szeged', bid: 'km', dur: '2 tahun', bhs: 'Inggris', d: 'Program media di kota universitas yang tenang, dengan biaya hidup lebih murah lagi dibanding Budapest.', p: ['Biaya hidup lebih rendah dari Budapest', 'Suasana kota universitas', 'Berbahasa Inggris'] },
    ],
  },
  {
    slug: 'invest-your-talent-italy', k: 'Invest Your Talent in Italy', ng: 'Italia', b: 'Eropa',
    bid: ['si', 'ti', 'ar'], loa: 1, kerja: 0, ikat: 0, td: '11 Mei', st: 'tutup', u: 'investyourtalent.esteri.it',
    intro: 'Menggabungkan kuliah S2 dengan magang di perusahaan Italia. Cuma tiga area studi, jadi ilmu politik dan komunikasi otomatis nggak masuk.',
    fk: [['Area studi', 'Cuma tiga bidang'], ['Kampus', '24 universitas'], ['Nilai', 'Sampai €10.800'], ['Bahasa', 'Inggris level B2']],
    ceklis: [[1, 'Latar belakang teknik, arsitektur, atau ekonomi', 'Di luar itu nggak dilayani'], [1, 'Sudah diterima di kampus peserta', ''], [0, 'Sertifikat bahasa Inggris B2', 'Atau surat dari kampus S1 berbahasa Inggris'], [0, 'Dokumen pendukung bahasa Italia', ''], [0, 'Pastikan bukan lulusan kampus Italia', 'Termasuk kriteria diskualifikasi']],
    waktu: [['11 Mei', 'Tenggat aplikasi pukul 23.00 WIB', 0], ['Mei sampai Juni', 'Seleksi', 0], ['September', 'Kuliah dimulai', 0]],
    awas: 'Buat memperpanjang ke tahun kedua, kamu wajib mengumpulkan minimal 30 kredit dan rutin ikut kelas bahasa Italia. Ini bukan perpanjangan otomatis.',
    pcat: 'Ada sekitar 130 sampai 240 program di 24 kampus, semuanya berbahasa Inggris. Ini beberapa yang cocok dengan jurusan kita.',
    prog: [
      { slug: 'cse-polimi', n: 'MSc Computer Science and Engineering', kmp: 'Politecnico di Milano', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Kampus teknik nomor satu di Italia, berada di kota yang jadi pusat industri dan desain negara itu. Program IYT-nya sudah termasuk magang di perusahaan Italia.', p: ['Kampus teknik peringkat teratas di Italia', 'Magang di perusahaan jadi bagian program', 'Berbahasa Inggris penuh'] },
      { slug: 'arch-polimi', n: 'MSc Architecture', kmp: 'Politecnico di Milano', bid: 'ar', dur: '2 tahun', bhs: 'Inggris', d: 'Sekolah arsitektur dengan reputasi global, berada di kota yang jadi ibukota desain dunia. Milan Design Week terjadi persis di depan pintu kampus.', p: ['Reputasi global di arsitektur dan desain', 'Terhubung ke ekosistem desain Milan', 'Magang termasuk dalam program'] },
      { slug: 'ce-padova', n: 'MSc Computer Engineering', kmp: 'Universita degli Studi di Padova', bid: 'si', dur: '2 tahun', bhs: 'Inggris', d: 'Salah satu universitas tertua di dunia, berdiri sejak 1222. Programnya modern meski gedungnya berabad-abad, dan biaya hidup Padova lebih rendah dari Milan.', p: ['Universitas berusia lebih dari 800 tahun', 'Biaya hidup lebih murah dari Milan', 'Dekat dengan Venesia'] },
      { slug: 'arch-cafoscari', n: 'MSc Architecture and Innovation', kmp: 'Universita Ca Foscari Venezia', bid: 'ar', dur: '2 tahun', bhs: 'Inggris', d: 'Belajar arsitektur di Venesia berarti berhadapan langsung dengan persoalan kota yang tenggelam dan warisan bangunan yang rapuh. Konteks belajarnya nggak ada duanya.', p: ['Konteks kota Venesia yang unik', 'Menyentuh isu adaptasi iklim dan konservasi', 'Termasuk kampus peserta IYT'] },
      { slug: 'eng-brescia', n: 'MSc Engineering', kmp: 'Universita degli Studi di Brescia', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Kota industri di utara Italia dengan kaitan erat ke manufaktur. Kalau minat kamu ke arah teknologi terapan dan industri, lingkungannya mendukung.', p: ['Kaitan erat dengan industri manufaktur', 'Biaya hidup rendah', 'Kelas berukuran kecil'] },
    ],
  },
  {
    slug: 'maeci-italia', k: 'Beasiswa Pemerintah Italia', ng: 'Italia', b: 'Eropa',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 1, kerja: 0, ikat: 0, td: '26 Maret', st: 'tutup', u: 'studyinitaly.esteri.it',
    intro: 'Hibah dari Kementerian Luar Negeri Italia yang berlaku untuk S2, S3, sekolah seni, riset singkat, sampai kursus bahasa. Cakupan bidangnya jauh lebih luas dari IYT.',
    fk: [['Penyelenggara', 'MAECI Italia'], ['Nilai', '€10.800'], ['Durasi', 'Sembilan bulan'], ['Perpanjangan', 'Bisa']],
    ceklis: [[1, 'Ijazah dan transkrip', ''], [0, 'Surat penerimaan program tujuan', ''], [0, 'Sertifikat bahasa Italia atau Inggris', ''], [0, 'Proposal riset', 'Untuk jalur riset dan S3'], [0, 'Aplikasi lewat portal Study in Italy', '']],
    waktu: [['26 Maret', 'Tenggat aplikasi', 0], ['Mei sampai Juli', 'Seleksi', 0], ['1 November', 'Program dimulai', 0], ['31 Juli tahun berikutnya', 'Program berakhir', 0]],
    awas: 'Dana dicairkan bertahap dalam tiga termin, bukan sekaligus di awal. Siapkan dana talangan buat biaya kedatangan dan bulan-bulan pertama.',
    pcat: 'Berlaku di kampus negeri Italia mana pun, termasuk sekolah seni dan musik. Ini beberapa contoh.',
    prog: [
      { slug: 'polsci-bologna', n: 'MA Scienze Politiche', kmp: 'Universita di Bologna', bid: 'hi', dur: '2 tahun', bhs: 'Italia dan Inggris', d: 'Universitas tertua di dunia Barat, berdiri 1088. Program ilmu politiknya punya jalur berbahasa Inggris dan menyorot politik Mediterania serta Eropa Selatan.', p: ['Universitas tertua di dunia Barat', 'Ada jalur berbahasa Inggris', 'Fokus ke politik Mediterania'] },
      { slug: 'comm-sapienza', n: 'MA Communication Studies', kmp: 'Sapienza Universita di Roma', bid: 'km', dur: '2 tahun', bhs: 'Italia dan Inggris', d: 'Kampus terbesar di Eropa berdasarkan jumlah mahasiswa, berada di Roma. Program komunikasinya menyentuh media, budaya, dan kebijakan informasi.', p: ['Kampus terbesar di Eropa', 'Lokasi di Roma', 'Sebagian kelas berbahasa Italia'] },
      { slug: 'arch-firenze', n: 'MSc Architettura', kmp: 'Universita degli Studi di Firenze', bid: 'ar', dur: '2 tahun', bhs: 'Italia', d: 'Belajar arsitektur di Florence, kota yang praktis jadi museum arsitektur Renaisans terbuka. Pengantarnya bahasa Italia, jadi kursus bahasa jadi bagian penting persiapan.', p: ['Konteks arsitektur Renaisans', 'Pengantar bahasa Italia', 'Kuat di restorasi dan konservasi'] },
    ],
  },
  {
    slug: 'eiffel-excellence', k: 'Eiffel Excellence', ng: 'Prancis', b: 'Eropa',
    bid: ['si', 'ti', 'ar', 'hi'], loa: 1, kerja: 0, ikat: 0, td: '8 Januari', st: 'tutup', u: 'campusfrance.org',
    intro: 'Kamu nggak bisa daftar sendiri. Universitas Prancis yang harus mengajukan nama kamu, jadi hubungan dengan kampus tujuan harus dibangun jauh-jauh hari.',
    fk: [['Penyelenggara', 'Kemlu Prancis'], ['Tunjangan', '€1.200 sampai 2.100'], ['Biaya kuliah', 'Sering dibebaskan kampus'], ['Cara daftar', 'Lewat kampus']],
    ceklis: [[1, 'Ijazah dan transkrip', ''], [0, 'Hubungi kampus tujuan duluan', 'Mereka yang mengajukan nama kamu'], [0, 'Berkas lengkap sebelum tenggat internal kampus', 'Selalu lebih awal dari tenggat resmi'], [0, 'Sertifikat bahasa', 'Ikut bahasa pengantar program'], [0, 'Rencana studi dan karier', '']],
    waktu: [['Oktober sampai Desember', 'Tenggat internal kampus', 0], ['8 Januari', 'Tenggat pengajuan oleh kampus', 0], ['Maret sampai April', 'Pengumuman', 0], ['September', 'Kuliah dimulai', 0]],
    awas: 'Tenggat 8 Januari itu buat kampus, bukan buat kamu. Tenggat kamu adalah tenggat internal kampus tujuan, yang biasanya jatuh berbulan-bulan lebih awal.',
    pcat: 'Kampus yang mengajukan nama kamu. Hubungi bagian internasional mereka sebelum tenggat internal.',
    prog: [
      { slug: 'cs-paris-saclay', n: 'MSc Computer Science', kmp: 'Universite Paris-Saclay', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Gabungan beberapa institusi riset yang jadi salah satu pusat sains terbesar di Eropa. Kuat di AI, dengan banyak lab yang menerima mahasiswa internasional.', p: ['Salah satu pusat riset terbesar di Eropa', 'Kuat di kecerdasan buatan', 'Program berbahasa Inggris tersedia'] },
      { slug: 'ir-sciencespo', n: 'MA International Relations', kmp: 'Sciences Po Paris', bid: 'hi', dur: '2 tahun', bhs: 'Inggris dan Prancis', d: 'Kampus ilmu politik paling dikenal di Prancis, tempat banyak diplomat dan pejabat dididik. Program internasionalnya berbahasa Inggris penuh.', p: ['Kampus ilmu politik paling bergengsi di Prancis', 'Jalur berbahasa Inggris tersedia', 'Jaringan alumni di diplomasi Eropa'] },
      { slug: 'arch-ensa', n: 'MSc Architecture', kmp: 'ENSA Paris-Belleville', bid: 'ar', dur: '2 tahun', bhs: 'Prancis', d: 'Sekolah arsitektur negeri di Paris dengan penekanan pada arsitektur kota. Pengantarnya bahasa Prancis, jadi persiapan bahasa jadi syarat mutlak.', p: ['Sekolah arsitektur negeri di Paris', 'Pengantar bahasa Prancis', 'Fokus ke arsitektur perkotaan'] },
    ],
  },
  {
    slug: 'gates-cambridge', k: 'Gates Cambridge', ng: 'Inggris', b: 'Eropa',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 1, kerja: 0, ikat: 0, td: 'Desember', st: 'segera', u: 'gatescambridge.org',
    intro: 'Salah satu beasiswa paling kompetitif di dunia, cuma sekitar 90 penerima dari seluruh dunia tiap tahun. Aplikasinya menyatu dengan aplikasi masuk Cambridge.',
    fk: [['Pendana', 'Gates Foundation'], ['Kampus', 'University of Cambridge'], ['Tunjangan', 'GBP 20.000 lebih'], ['Penerima', 'Sekitar 90 setahun']],
    ceklis: [[1, 'Melamar program Cambridge dulu', 'Aplikasi beasiswa menyatu dengan aplikasi kampus'], [0, 'Statement penelitian', ''], [0, 'Surat rekomendasi akademik', ''], [0, 'Bukti komitmen dampak sosial', 'Kriteria khas program ini'], [0, 'Latihan wawancara', '']],
    waktu: [['Oktober sampai Desember', 'Tenggat beda tiap jurusan', 0], ['Januari sampai Februari', 'Seleksi berkas', 0], ['Maret', 'Wawancara', 0], ['Maret sampai April', 'Pengumuman', 0]],
    awas: 'Tenggatnya ikut jurusan yang kamu lamar, bukan satu tanggal seragam. Sebagian jurusan menutup pendaftaran di awal Desember.',
    pcat: 'Berlaku untuk semua program pascasarjana Cambridge. Ini yang paling nyambung dengan jurusan kita.',
    prog: [
      { slug: 'acs-cambridge', n: 'MPhil Advanced Computer Science', kmp: 'University of Cambridge', bid: 'ti', dur: '1 tahun', bhs: 'Inggris', d: 'Program riset intensif satu tahun yang sering jadi batu loncatan ke PhD. Beban bacaannya berat dan sangat berorientasi penelitian.', p: ['Sangat berorientasi riset', 'Sering jadi jalur menuju PhD', 'Tenggat jatuh awal Desember'] },
      { slug: 'ir-cambridge', n: 'MPhil International Relations and Politics', kmp: 'University of Cambridge', bid: 'hi', dur: '1 tahun', bhs: 'Inggris', d: 'Program HI dengan pendekatan teoretis yang kuat. Cocok kalau kamu berencana lanjut ke jenjang doktoral atau masuk dunia akademik.', p: ['Pendekatan teoretis yang kuat', 'Kelas berukuran kecil', 'Sistem college memberi jaringan lintas bidang'] },
      { slug: 'arch-cambridge', n: 'MPhil Architecture and Urban Studies', kmp: 'University of Cambridge', bid: 'ar', dur: '1 tahun', bhs: 'Inggris', d: 'Menggabungkan sejarah arsitektur dengan studi kota. Lebih ke arah riset dan teori ketimbang praktik studio.', p: ['Lebih riset daripada praktik studio', 'Menggabungkan sejarah dan studi kota', 'Akses ke arsip dan perpustakaan Cambridge'] },
    ],
  },
  {
    slug: 'rhodes-scholarship', k: 'Rhodes Scholarship', ng: 'Inggris', b: 'Eropa',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 1, kerja: 0, ikat: 0, td: 'Agustus', st: 'buka', u: 'rhodeshouse.ox.ac.uk',
    intro: 'Beasiswa tertua di dunia, jalan sejak 1903. Kuotanya dialokasikan per wilayah, jadi cek dulu apakah Indonesia masuk konstituensi tahun ini.',
    fk: [['Pengelola', 'Rhodes Trust'], ['Kampus', 'University of Oxford'], ['Berdiri', '1903'], ['Jenjang', 'S2 dan S3']],
    ceklis: [[1, 'Ijazah S1 dengan prestasi menonjol', ''], [0, 'Bukti kepemimpinan dan pelayanan', 'Kriteria inti sejak program berdiri'], [0, 'Surat rekomendasi', ''], [0, 'Melamar program Oxford terpisah', ''], [0, 'Latihan wawancara panel', '']],
    waktu: [['Agustus', 'Pendaftaran dibuka', 1], ['Oktober', 'Tenggat aplikasi', 0], ['November sampai Desember', 'Wawancara', 0], ['Desember', 'Pengumuman', 0]],
    awas: 'Kuota dialokasikan per wilayah, bukan per individu global. Cek apakah Indonesia termasuk konstituensi yang dibuka di siklus tahun berjalan.',
    pcat: 'Berlaku untuk semua program pascasarjana Oxford.',
    prog: [
      { slug: 'cs-oxford', n: 'MSc Computer Science', kmp: 'University of Oxford', bid: 'ti', dur: '1 tahun', bhs: 'Inggris', d: 'Program satu tahun yang padat, dengan pilihan mata kuliah dari teori komputasi sampai machine learning terapan.', p: ['Padat dalam satu tahun', 'Pilihan mata kuliah luas', 'Sistem tutorial khas Oxford'] },
      { slug: 'ir-oxford', n: 'MPhil International Relations', kmp: 'University of Oxford', bid: 'hi', dur: '2 tahun', bhs: 'Inggris', d: 'Program HI dua tahun yang lebih dalam dari MSc setahun. Banyak alumninya masuk ke lembaga internasional dan diplomasi.', p: ['Dua tahun, lebih dalam dari program setahun', 'Jaringan alumni di lembaga internasional', 'Sistem college Oxford'] },
      { slug: 'media-oxford', n: 'MSc Media, Communication and Development', kmp: 'University of Oxford', bid: 'km', dur: '1 tahun', bhs: 'Inggris', d: 'Menyorot peran media dalam pembangunan dan perubahan sosial, bukan media sebagai industri. Relevan buat yang bekerja di organisasi masyarakat sipil.', p: ['Fokus media dalam konteks pembangunan', 'Relevan untuk kerja di sektor sosial', 'Berbasis studi kasus negara berkembang'] },
    ],
  },
  {
    slug: 'daad', k: 'DAAD', ng: 'Jerman', b: 'Eropa',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 1, kerja: 0, ikat: 0, td: 'Bervariasi', st: 'segera', u: 'daadjkt.org',
    intro: 'DAAD itu payung dari puluhan skema berbeda. Bilang mau daftar DAAD tanpa menyebut skemanya berarti belum benar-benar mulai.',
    fk: [['Penyelenggara', 'DAAD Jerman'], ['Tunjangan', '€850 sampai 1.200'], ['Jumlah skema', 'Puluhan'], ['Kantor Indonesia', 'DAAD Jakarta']],
    ceklis: [[1, 'Tentukan skema yang tepat duluan', 'Ini langkah yang paling sering dilewati'], [0, 'Ijazah dan transkrip', ''], [0, 'Sertifikat bahasa', 'Jerman atau Inggris, tergantung program'], [0, 'Surat rekomendasi', ''], [0, 'Cek tenggat skema pilihan', 'Beda total antar program']],
    waktu: [['Bervariasi', 'Tiap skema punya kalender sendiri', 0]],
    awas: 'Skema Helmut Schmidt, EPOS, dan lainnya punya sasaran pelamar yang sangat beda. Salah pilih skema berarti membuang satu siklus penuh.',
    pcat: 'Program di bawah ini masuk skema EPOS atau Helmut Schmidt, yang paling relevan buat pelamar Indonesia.',
    prog: [
      { slug: 'cs-tum', n: 'MSc Computer Science', kmp: 'Technical University of Munich', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Salah satu kampus teknik terbaik di Eropa. Banyak program pascasarjananya berbahasa Inggris, dan biaya kuliah di kampus negeri Jerman praktis nol.', p: ['Kampus teknik peringkat teratas Jerman', 'Banyak program berbahasa Inggris', 'Biaya kuliah kampus negeri sangat rendah'] },
      { slug: 'pp-hertie', n: 'MA Public Policy', kmp: 'Hertie School Berlin', bid: 'hi', dur: '2 tahun', bhs: 'Inggris', d: 'Sekolah kebijakan publik di Berlin dengan pengantar bahasa Inggris penuh. Masuk daftar program yang didanai skema Helmut Schmidt.', p: ['Termasuk skema Helmut Schmidt Programme', 'Berbahasa Inggris penuh', 'Lokasi di pusat kebijakan Berlin'] },
      { slug: 'arch-bauhaus', n: 'MSc Architecture', kmp: 'Bauhaus-Universitat Weimar', bid: 'ar', dur: '2 tahun', bhs: 'Inggris dan Jerman', d: 'Kampus yang jadi tempat lahirnya gerakan Bauhaus, salah satu tonggak arsitektur modern. Pendekatannya masih eksperimental sampai sekarang.', p: ['Tempat lahirnya gerakan Bauhaus', 'Pendekatan eksperimental', 'Sebagian program berbahasa Inggris'] },
      { slug: 'ims-bonn', n: 'MA International Media Studies', kmp: 'University of Bonn dan Deutsche Welle', bid: 'km', dur: '2 tahun', bhs: 'Inggris dan Jerman', d: 'Kerja sama antara universitas dan lembaga penyiaran internasional Jerman. Ada porsi praktik di ruang redaksi sungguhan.', p: ['Kerja sama dengan Deutsche Welle', 'Ada praktik di ruang redaksi', 'Menggabungkan teori dan produksi media'] },
    ],
  },
  {
    slug: 'swedish-institute', k: 'Swedish Institute', ng: 'Swedia', b: 'Eropa',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 1, kerja: 2, ikat: 0, td: 'Februari', st: 'segera', u: 'si.se',
    intro: 'Yang dicari program ini adalah pengalaman kepemimpinan, bukan cuma prestasi akademik. Urutannya juga nggak bisa dibalik: daftar kampus dulu, baru beasiswa.',
    fk: [['Penyelenggara', 'Swedish Institute'], ['Transportasi', 'SEK 15.000 sekali bayar'], ['Jaringan', 'NFGL leadership network'], ['Urutan', 'Kampus dulu, beasiswa kemudian']],
    ceklis: [[1, 'Pengalaman kepemimpinan', 'Dari kerja atau organisasi masyarakat sipil'], [1, 'Daftar program master kampus duluan', ''], [0, 'Aplikasi lewat portal SI Scholarship', 'Dibuka sekitar Februari'], [0, 'Sertifikat bahasa', ''], [0, 'Surat rekomendasi', '']],
    waktu: [['Oktober sampai Januari', 'Pendaftaran program master', 0], ['Februari', 'Portal beasiswa dibuka', 0], ['April', 'Pengumuman', 0], ['Agustus', 'Kuliah dimulai', 0]],
    awas: 'Aplikasi beasiswa merujuk nomor pendaftaran kampus. Jadi kalau kamu belum melamar program master waktu portal beasiswa buka, kamu nggak bisa ikut sama sekali.',
    pcat: 'Daftar programnya lewat universityadmissions.se, baru ajukan beasiswanya.',
    prog: [
      { slug: 'cs-kth', n: 'MSc Computer Science', kmp: 'KTH Royal Institute of Technology', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Kampus teknik utama Swedia, berada di Stockholm. Terhubung erat dengan ekosistem startup Stockholm yang melahirkan Spotify dan Klarna.', p: ['Kampus teknik utama Swedia', 'Dekat ekosistem startup Stockholm', 'Berbahasa Inggris penuh'] },
      { slug: 'urban-kth', n: 'MSc Sustainable Urban Planning and Design', kmp: 'KTH Royal Institute of Technology', bid: 'ar', dur: '2 tahun', bhs: 'Inggris', d: 'Perencanaan kota berkelanjutan, bidang yang jadi keahlian khas negara Nordik. Banyak studi kasus diambil dari kota-kota Swedia sendiri.', p: ['Fokus keberlanjutan, keahlian khas Nordik', 'Studi kasus dari kota Swedia', 'Berbahasa Inggris'] },
      { slug: 'global-lund', n: 'MSc Global Studies', kmp: 'Lund University', bid: 'hi', dur: '2 tahun', bhs: 'Inggris', d: 'Program lintas bidang yang menggabungkan politik, ekonomi, dan sosiologi dalam kerangka global. Lund termasuk kampus tertua di Skandinavia.', p: ['Pendekatan lintas bidang', 'Kampus tertua di Skandinavia', 'Biaya hidup lebih murah dari Stockholm'] },
      { slug: 'media-stockholm', n: 'MSc Media and Communication Studies', kmp: 'Stockholm University', bid: 'km', dur: '2 tahun', bhs: 'Inggris', d: 'Program media dengan penekanan pada demokrasi dan ruang publik, tema yang jadi perhatian besar di negara Nordik.', p: ['Menyorot media dan demokrasi', 'Lokasi di Stockholm', 'Berbahasa Inggris'] },
    ],
  },
  {
    slug: 'eric-bleumink-fund', k: 'Eric Bleumink Fund', ng: 'Belanda', b: 'Eropa',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 1, kerja: 0, ikat: 0, td: 'Bervariasi', st: 'segera', u: 'rug.nl',
    intro: 'Beasiswa penuh dari University of Groningen. Terikat ke satu kampus, jadi kalau nggak ada program yang cocok, nggak ada jalur alternatif.',
    fk: [['Penyelenggara', 'University of Groningen'], ['Jenjang', 'S2'], ['Pendanaan', 'Penuh'], ['Sasaran', 'Mahasiswa internasional']],
    ceklis: [[1, 'Melamar program master Groningen duluan', ''], [0, 'Ijazah dan transkrip', ''], [0, 'Sertifikat bahasa Inggris', ''], [0, 'Motivation letter', ''], [0, 'Surat rekomendasi', '']],
    waktu: [['Bervariasi', 'Ikut kalender penerimaan kampus', 0]],
    awas: 'Beasiswa ini terikat pada satu kampus. Kalau Groningen nggak punya program yang cocok dengan bidang kamu, nggak ada jalur cadangan di dalam skema yang sama.',
    pcat: 'Semua program ada di University of Groningen.',
    prog: [
      { slug: 'cs-groningen', n: 'MSc Computing Science', kmp: 'University of Groningen', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Program ilmu komputer dengan pilihan peminatan di sistem cerdas dan ilmu data. Groningen dikenal sebagai kota mahasiswa dengan biaya hidup terkendali.', p: ['Peminatan di sistem cerdas dan ilmu data', 'Kota mahasiswa dengan biaya hidup terkendali', 'Berbahasa Inggris'] },
      { slug: 'is-groningen', n: 'MSc Information Science', kmp: 'University of Groningen', bid: 'si', dur: '1 tahun', bhs: 'Inggris', d: 'Lebih dekat ke sisi manusia dan informasi ketimbang rekayasa perangkat lunak. Cukup ditempuh satu tahun.', p: ['Cuma satu tahun', 'Fokus ke sisi manusia dan informasi', 'Cocok untuk latar Sistem Informasi'] },
      { slug: 'ir-groningen', n: 'MA International Relations', kmp: 'University of Groningen', bid: 'hi', dur: '1 tahun', bhs: 'Inggris', d: 'Program HI setahun dengan beberapa jalur peminatan, termasuk keamanan internasional dan ekonomi politik global.', p: ['Setahun dengan beberapa peminatan', 'Termasuk keamanan dan ekonomi politik', 'Berbahasa Inggris'] },
    ],
  },
  {
    slug: 'swiss-excellence', k: 'Swiss Government Excellence', ng: 'Swiss', b: 'Eropa',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 1, kerja: 0, ikat: 0, td: 'Bervariasi', st: 'segera', u: 'sbfi.admin.ch',
    intro: 'Menanggung penuh studi di negara dengan biaya hidup tertinggi di Eropa. Lebih condong ke jalur riset, dan dukungan calon pembimbing sering jadi penentu.',
    fk: [['Penyelenggara', 'Pemerintah Swiss'], ['Tunjangan', 'CHF 1.920 sebulan'], ['Biaya kuliah', 'Dibebaskan'], ['Syarat', 'Beda tiap kampus']],
    ceklis: [[1, 'Ijazah dan transkrip', ''], [0, 'Cek syarat kampus tujuan', 'Sangat bervariasi'], [0, 'Proposal riset', ''], [0, 'Surat dukungan profesor tujuan', 'Sering jadi penentu'], [0, 'Aplikasi lewat Kedutaan Swiss', '']],
    waktu: [['Bervariasi', 'Umumnya tenggat sekitar akhir tahun', 0]],
    awas: 'Dukungan dari calon pembimbing di kampus Swiss sering lebih menentukan daripada nilai akademik kamu. Bangun kontak itu duluan.',
    pcat: 'Dua kampus federal Swiss jadi tujuan paling umum.',
    prog: [
      { slug: 'cs-ethz', n: 'MSc Computer Science', kmp: 'ETH Zurich', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Salah satu kampus teknik terbaik di dunia, dan biaya kuliahnya justru sangat rendah karena berstatus kampus federal.', p: ['Peringkat teratas dunia untuk teknik', 'Biaya kuliah sangat rendah', 'Berbahasa Inggris penuh'] },
      { slug: 'arch-ethz', n: 'MSc Architecture', kmp: 'ETH Zurich', bid: 'ar', dur: '2 tahun', bhs: 'Jerman dan Inggris', d: 'Sekolah arsitektur dengan reputasi global, dikenal karena ketelitian teknis dan pendekatan berbasis material.', p: ['Reputasi global di arsitektur', 'Kuat di sisi teknis dan material', 'Sebagian kelas berbahasa Jerman'] },
      { slug: 'ia-geneva', n: 'MA International Affairs', kmp: 'Graduate Institute Geneva', bid: 'hi', dur: '2 tahun', bhs: 'Inggris dan Prancis', d: 'Berada persis di kota yang jadi markas banyak lembaga PBB. Kesempatan magang dan jaringan di lembaga internasional sangat terbuka.', p: ['Lokasi di pusat lembaga internasional', 'Peluang magang di lembaga PBB', 'Dwibahasa Inggris dan Prancis'] },
    ],
  },
  {
    slug: 'fulbright', k: 'Fulbright', ng: 'Amerika Serikat', b: 'Amerika',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 0, kerja: 0, ikat: 1, td: '18 Februari', st: 'tutup', u: 'aminef.or.id',
    intro: 'Dikelola AMINEF sejak 1952, dengan lebih dari 3.000 alumni Indonesia. Kamu nggak memilih kampus sendiri, AMINEF yang menempatkan setelah kamu lolos.',
    fk: [['Pengelola', 'AMINEF'], ['Awardee 2024', '127 orang Indonesia'], ['IPK minimum', '3,00'], ['Ikatan', 'Pulang dan kerja 5 tahun']],
    ceklis: [[1, 'IPK minimum 3,00', ''], [1, 'TOEFL ITP 550 atau IELTS 6,5', 'Atau Duolingo 125'], [0, 'Study objective satu halaman', ''], [0, 'Personal statement satu halaman', ''], [0, 'Dua surat rekomendasi', 'Dari atasan atau dosen']],
    waktu: [['Februari', 'Tenggat aplikasi', 0], ['Mei sampai Juni', 'Wawancara', 0], ['Juli sampai Desember', 'Penempatan kampus oleh AMINEF', 0], ['Agustus tahun berikutnya', 'Berangkat', 0]],
    awas: 'Fleksibilitas soal kampus tujuan itu bagian dari kesepakatan. Kalau kamu punya satu kampus impian dan nggak mau yang lain, jalur ini mungkin bukan buat kamu.',
    pcat: 'AMINEF yang menempatkan kamu. Ini bidang studi yang paling sering diambil awardee Indonesia, bukan daftar kampus.',
    prog: [
      { slug: 'mpp-aminef', n: 'Master of Public Policy', kmp: 'Ditempatkan AMINEF', bid: 'hi', dur: '2 tahun', bhs: 'Inggris', d: 'Salah satu bidang paling populer di kalangan awardee Indonesia. AMINEF menempatkan kamu di kampus yang sesuai profil dan rencana studi yang kamu ajukan.', p: ['Bidang favorit awardee Indonesia', 'Kampus ditentukan AMINEF setelah lolos', 'Durasi satu sampai dua tahun'] },
      { slug: 'cs-aminef', n: 'MS Computer Science', kmp: 'Ditempatkan AMINEF', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Jalur teknis yang terbuka lebar karena Fulbright nggak membatasi bidang, kecuali kedokteran yang menyentuh perawatan pasien langsung.', p: ['Fulbright nggak membatasi bidang STEM', 'Kampus ditentukan setelah seleksi', 'Bisa diarahkan ke peminatan tertentu'] },
      { slug: 'march-aminef', n: 'Master of Architecture', kmp: 'Ditempatkan AMINEF', bid: 'ar', dur: '2 sampai 3 tahun', bhs: 'Inggris', d: 'Program arsitektur di AS sering berdurasi lebih panjang karena terkait akreditasi profesi. Perhatikan ini waktu menyusun rencana studi.', p: ['Durasi bisa lebih dari dua tahun', 'Terkait akreditasi profesi di AS', 'Kampus ditentukan AMINEF'] },
      { slug: 'comm-aminef', n: 'MA Communication', kmp: 'Ditempatkan AMINEF', bid: 'km', dur: '2 tahun', bhs: 'Inggris', d: 'Bidang komunikasi terbuka penuh di Fulbright, berbeda dengan banyak beasiswa berbasis prioritas nasional yang menutupnya.', p: ['Terbuka penuh, tidak dibatasi prioritas nasional', 'Kampus ditentukan AMINEF', 'Bisa mengarah ke jurnalisme atau media digital'] },
    ],
  },
  {
    slug: 'knight-hennessy', k: 'Knight-Hennessy Scholars', ng: 'Amerika Serikat', b: 'Amerika',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 1, kerja: 0, ikat: 0, td: 'Oktober', st: 'buka', u: 'knight-hennessy.stanford.edu',
    intro: 'Berlaku untuk semua program pascasarjana di Stanford, lintas fakultas. Repotnya, tenggat beasiswa jatuh lebih awal dari tenggat programnya.',
    fk: [['Kampus', 'Stanford University'], ['Cakupan', 'Semua program pascasarjana'], ['Pendanaan', 'Penuh'], ['Tenggat', 'Sekitar Oktober']],
    ceklis: [[1, 'Melamar program Stanford terpisah', 'Dua aplikasi berbeda'], [0, 'Esai kepemimpinan', ''], [0, 'Surat rekomendasi', ''], [0, 'Rekam jejak dampak', ''], [0, 'Latihan wawancara', '']],
    waktu: [['Oktober', 'Tenggat aplikasi beasiswa', 1], ['Desember sampai Januari', 'Tenggat aplikasi program Stanford', 0], ['Februari', 'Wawancara', 0], ['Maret', 'Pengumuman', 0]],
    awas: 'Kamu harus menyiapkan aplikasi beasiswa sebelum tahu diterima atau nggak di programnya. Ini menuntut komitmen waktu di muka tanpa jaminan apa pun.',
    pcat: 'Semua program pascasarjana Stanford masuk. Ini yang paling nyambung dengan jurusan kita.',
    prog: [
      { slug: 'cs-stanford', n: 'MS Computer Science', kmp: 'Stanford University', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Berada persis di jantung Silicon Valley. Banyak mahasiswanya menjalankan proyek atau perusahaan sambil kuliah.', p: ['Lokasi di jantung Silicon Valley', 'Peminatan sangat beragam', 'Kaitan erat dengan industri teknologi'] },
      { slug: 'ip-stanford', n: 'MA International Policy', kmp: 'Stanford University', bid: 'hi', dur: '2 tahun', bhs: 'Inggris', d: 'Program kebijakan internasional yang terhubung ke lembaga riset seperti Freeman Spogli Institute.', p: ['Terhubung ke lembaga riset kebijakan', 'Bisa digabung dengan program lain', 'Fokus kebijakan terapan'] },
      { slug: 'comm-stanford', n: 'MS Communication', kmp: 'Stanford University', bid: 'km', dur: '1 sampai 2 tahun', bhs: 'Inggris', d: 'Program komunikasi yang banyak bersinggungan dengan teknologi, terutama soal dampak media digital terhadap masyarakat.', p: ['Bersinggungan erat dengan teknologi', 'Riset dampak media digital', 'Kelas kecil'] },
    ],
  },
  {
    slug: 'mccall-macbain', k: 'McCall MacBain', ng: 'Kanada', b: 'Amerika',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 1, kerja: 0, ikat: 0, td: 'Agustus', st: 'buka', u: 'mccallmacbainscholars.org',
    intro: 'Mencakup lebih dari 150 bidang di McGill, termasuk kursus bahasa Prancis dari nol. Juga menerima pelamar untuk gelar sarjana profesional kedua.',
    fk: [['Kampus', 'McGill University'], ['Bidang', '150 lebih'], ['Tunjangan', 'CAD 2.300 sebulan'], ['Tambahan', 'Relokasi dan kursus Prancis']],
    ceklis: [[1, 'Melamar program McGill terpisah', ''], [0, 'Esai kepemimpinan', ''], [0, 'Surat rekomendasi', ''], [0, 'Rencana inisiatif musim panas', 'Bisa didanai sampai CAD 5.000'], [0, 'Latihan wawancara regional', '']],
    waktu: [['Agustus', 'Pendaftaran dibuka', 1], ['September sampai Oktober', 'Tenggat aplikasi', 0], ['November sampai Januari', 'Wawancara regional', 0], ['Maret', 'Pengumuman', 0]],
    awas: 'Program ini juga menerima pelamar untuk gelar sarjana profesional kedua, bukan cuma master. Kalau kamu mempertimbangkan pindah jalur profesi, cek kategori ini.',
    pcat: 'Lebih dari 150 program di McGill. Ini yang paling nyambung dengan jurusan kita.',
    prog: [
      { slug: 'cs-mcgill', n: 'MSc Computer Science', kmp: 'McGill University', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Montreal jadi salah satu pusat riset AI dunia, terutama karena keberadaan Mila. Ekosistemnya kuat meski biaya hidupnya jauh lebih rendah dari kota besar AS.', p: ['Montreal sebagai pusat riset AI', 'Biaya hidup lebih rendah dari kota besar AS', 'Kursus bahasa Prancis disediakan'] },
      { slug: 'arch-mcgill', n: 'MArch Architecture', kmp: 'McGill University', bid: 'ar', dur: '2 tahun', bhs: 'Inggris', d: 'Sekolah arsitektur yang menyorot iklim dingin dan bangunan hemat energi, tema yang jadi keahlian khas Kanada.', p: ['Kuat di bangunan hemat energi iklim dingin', 'Kota dwibahasa', 'Termasuk dalam 150 bidang yang didanai'] },
      { slug: 'polsci-mcgill', n: 'MA Political Science', kmp: 'McGill University', bid: 'hi', dur: '2 tahun', bhs: 'Inggris', d: 'Program ilmu politik dengan kekuatan di politik komparatif dan federalisme, tema yang hidup betul di konteks Kanada.', p: ['Kuat di politik komparatif dan federalisme', 'Konteks Kanada yang relevan', 'Kelas berukuran sedang'] },
      { slug: 'comm-mcgill', n: 'MA Communication Studies', kmp: 'McGill University', bid: 'km', dur: '2 tahun', bhs: 'Inggris', d: 'Program komunikasi dengan pendekatan kritis dan budaya. Montreal punya lanskap media dwibahasa yang jadi bahan studi menarik.', p: ['Pendekatan kritis dan studi budaya', 'Lanskap media dwibahasa Montreal', 'Bisa didanai penuh lewat beasiswa ini'] },
    ],
  },
  {
    slug: 'lpdp-australia-awards', k: 'LPDP Australia Awards', ng: 'Australia', b: 'Oseania',
    bid: ['si', 'ti'], loa: 0, kerja: 0, ikat: 1, td: '4 Mei', st: 'tutup', u: 'beasiswalpdp.kemenkeu.go.id',
    intro: 'Kerja sama LPDP dan Pemerintah Australia. Nggak perlu surat penerimaan, cukup pilih tiga kampus dari daftar dan pendaftarannya diurus setelah kamu lolos.',
    fk: [['Kampus', '30 perguruan tinggi'], ['Batas usia', '42 tahun'], ['IPK minimum', '3,00'], ['Bidang', 'Tujuh prioritas nasional']],
    ceklis: [[1, 'IPK minimum 3,00', 'Transkrip asli atau legalisir'], [1, 'Usia maksimal 42 tahun', 'Per 31 Desember tahun pendaftaran'], [0, 'Pilih tiga kampus dan prodi', 'Dari daftar resmi LPDP'], [0, 'Esai komitmen kembali ke Indonesia', 'Termasuk rencana pengabdian di industri'], [0, 'Belum pernah menyelesaikan S2', 'Lulusan S2 nggak boleh daftar jalur magister']],
    waktu: [['2 April', 'Pendaftaran dibuka', 0], ['4 Mei', 'Pendaftaran ditutup', 0], ['Juni', 'Pengumuman hasil sanggah', 0], ['2027', 'Kuliah dimulai', 0]],
    awas: 'Cuma tujuh bidang prioritas yang dibuka. Arsitektur, ilmu politik, dan ilmu komunikasi nggak termasuk, jadi jalur ini tertutup buat tiga dari lima jurusan kita.',
    pcat: 'Ada 30 kampus di daftar resmi, tapi cuma bidang prioritas yang dibuka. Ini yang cocok dengan Sistem Informasi dan Teknik Informatika.',
    prog: [
      { slug: 'ai-monash', n: 'Master of Artificial Intelligence', kmp: 'Monash University', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Masuk bidang prioritas Digitalisasi yang mencakup AI dan semikonduktor. Monash termasuk kampus mitra Australia Awards yang paling sering dipilih.', p: ['Masuk bidang prioritas Digitalisasi', 'Kampus mitra Australia Awards', 'Durasi 24 bulan single degree'] },
      { slug: 'it-sydney', n: 'Master of Information Technology', kmp: 'The University of Sydney', bid: 'si', dur: '2 tahun', bhs: 'Inggris', d: 'Program TI dengan peminatan yang bisa diarahkan ke sistem informasi atau ilmu data. Sydney termasuk daftar kampus mitra.', p: ['Peminatan bisa diarahkan ke sistem informasi', 'Termasuk kampus mitra', 'Masuk bidang prioritas Digitalisasi'] },
      { slug: 'computing-anu', n: 'Master of Computing', kmp: 'Australian National University', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'ANU berada di Canberra, dekat dengan pusat pemerintahan Australia. Programnya kuat di sisi riset dan komputasi ilmiah.', p: ['Kuat di riset dan komputasi ilmiah', 'Lokasi di Canberra', 'Termasuk kampus mitra'] },
      { slug: 'ds-macquarie', n: 'Master of Data Science', kmp: 'Macquarie University', bid: 'si', dur: '2 tahun', bhs: 'Inggris', d: 'Program ilmu data yang menyeimbangkan sisi teknis dengan penerapan bisnis. Macquarie termasuk daftar 30 kampus mitra.', p: ['Seimbang antara teknis dan bisnis', 'Termasuk kampus mitra', 'Masuk bidang prioritas'] },
    ],
  },
  {
    slug: 'manaaki-new-zealand', k: 'Manaaki New Zealand', ng: 'Selandia Baru', b: 'Oseania',
    bid: ['si', 'ti', 'hi', 'km'], loa: 0, kerja: 0, ikat: 1, td: '18 Februari', st: 'tutup', u: 'nzscholarships.govt.nz',
    intro: 'Program pemerintah Selandia Baru untuk pelajar dari negara berkembang, dengan penekanan besar pada kontribusi pembangunan setelah pulang.',
    fk: [['Penyelenggara', 'Pemerintah Selandia Baru'], ['Jenjang', 'S2'], ['Pendanaan', 'Penuh'], ['Ikatan', 'Kerja 5 tahun']],
    ceklis: [[1, 'Kesediaan menerima ikatan', 'Kerja minimal lima tahun sebelum pensiun'], [0, 'Ijazah dan transkrip', ''], [0, 'Sertifikat bahasa Inggris', ''], [0, 'Esai rencana kontribusi', ''], [0, 'Surat rekomendasi', '']],
    waktu: [['Februari', 'Tenggat aplikasi', 0], ['Maret sampai Juni', 'Seleksi', 0], ['Juli', 'Pengumuman', 0], ['Awal tahun berikutnya', 'Kuliah dimulai', 0]],
    awas: 'Ikatan lima tahun di sini dihitung sampai masa pensiun, bukan lima tahun sejak lulus. Baca ketentuannya baik-baik sebelum tanda tangan.',
    pcat: 'Delapan kampus negeri Selandia Baru masuk daftar. Ini beberapa yang relevan.',
    prog: [
      { slug: 'it-auckland', n: 'Master of Information Technology', kmp: 'University of Auckland', bid: 'si', dur: '1 sampai 2 tahun', bhs: 'Inggris', d: 'Kampus terbesar Selandia Baru, berada di kota terbesarnya. Program TI-nya punya jalur untuk lulusan non-komputer.', p: ['Kampus terbesar Selandia Baru', 'Ada jalur untuk lulusan non-komputer', 'Lokasi di Auckland'] },
      { slug: 'ir-victoria', n: 'Master of International Relations', kmp: 'Victoria University of Wellington', bid: 'hi', dur: '1 sampai 2 tahun', bhs: 'Inggris', d: 'Berada di ibukota, dekat dengan kementerian dan lembaga pemerintah. Fokusnya banyak ke kawasan Pasifik.', p: ['Lokasi di ibukota Wellington', 'Fokus ke kawasan Pasifik', 'Dekat lembaga pemerintah'] },
      { slug: 'comm-canterbury', n: 'Master of Communication', kmp: 'University of Canterbury', bid: 'km', dur: '1 sampai 2 tahun', bhs: 'Inggris', d: 'Program komunikasi dengan penekanan pada komunikasi risiko dan bencana, bidang yang berkembang di Christchurch setelah gempa besar 2011.', p: ['Kuat di komunikasi risiko dan bencana', 'Relevan untuk konteks Indonesia', 'Biaya hidup lebih rendah'] },
    ],
  },
  {
    slug: 'lpdp-reguler', k: 'LPDP Reguler', ng: 'Lintas negara', b: 'semua',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 1, kerja: 0, ikat: 1, td: '31 Juli', st: 'tutup', u: 'lpdp.kemenkeu.go.id',
    intro: 'Beasiswa pemerintah Indonesia yang berlaku hampir ke semua negara, dengan pendanaan paling lengkap di daftar ini. Tapi 2026 alokasinya bergeser besar ke STEM.',
    fk: [['Penyelenggara', 'LPDP Kemenkeu'], ['Gelombang', 'Dua sampai tiga setahun'], ['Bahasa', 'TOEFL ITP 500'], ['Alokasi 2026', '80 persen ke STEM']],
    ceklis: [[1, 'LoA unconditional dari kampus tujuan', 'Untuk jalur reguler luar negeri'], [1, 'TOEFL ITP 500 atau IELTS 6.0', ''], [0, 'Cek daftar perguruan tinggi tujuan', 'Diperbarui tiap tahun'], [0, 'Esai komitmen kontribusi', ''], [0, 'Rencana studi dan pasca studi', '']],
    waktu: [['Januari sampai Februari', 'Gelombang pertama', 0], ['Juni sampai Juli', 'Gelombang kedua', 0], ['Setelah tiap gelombang', 'Seleksi substansi dan wawancara', 0]],
    awas: 'Daftar kampus unggulan 2026 dipangkas dari 30 jadi 17 institusi. Kalau kampus incaran kamu ada di daftar tahun lalu, cek ulang apakah masih masuk tahun ini.',
    pcat: 'Ada 181 kampus di daftar tujuan luar negeri. Ini kampus yang paling sering dipilih awardee untuk lima jurusan kita.',
    prog: [
      { slug: 'analytics-nus', n: 'MSc Analytics dan Business Analytics', kmp: 'National University of Singapore', bid: 'si', dur: '1 sampai 2 tahun', bhs: 'Inggris', d: 'NUS jadi tujuan paling populer awardee LPDP, terutama untuk teknologi, bisnis, dan ilmu sosial. Dekat dari Indonesia dan masuk daftar kampus kemitraan.', p: ['Tujuan terpopuler awardee LPDP', 'Masuk daftar kampus kemitraan', 'Dekat dari Indonesia'] },
      { slug: 'ai-ntu', n: 'MSc Computer Engineering dan AI', kmp: 'Nanyang Technological University', bid: 'ti', dur: '1 sampai 2 tahun', bhs: 'Inggris', d: 'Kampus riset dengan fasilitas sangat modern, jadi favorit awardee di bidang teknik dan AI. Termasuk daftar kampus kemitraan LPDP.', p: ['Fasilitas riset sangat modern', 'Masuk daftar kampus kemitraan', 'Kuat di teknik dan AI'] },
      { slug: 'ai-kaist-lpdp', n: 'MSc Artificial Intelligence', kmp: 'KAIST', bid: 'ti', dur: '2 tahun', bhs: 'Inggris', d: 'Kampus teknologi terbaik Korea yang juga bisa diakses lewat jalur GKS. Jadi ada dua sumber pendanaan menuju tempat yang sama.', p: ['Bisa diakses lewat LPDP atau GKS', 'Kuat di AI dan robotika', 'Berbahasa Inggris penuh'] },
      { slug: 'pp-oxford-lpdp', n: 'MSc Public Policy', kmp: 'University of Oxford', bid: 'hi', dur: '1 tahun', bhs: 'Inggris', d: 'Termasuk kampus unggulan LPDP. Ingat bahwa daftar kampus unggulan 2026 dipangkas jadi 17, jadi verifikasi statusnya sebelum menyusun rencana.', p: ['Termasuk kampus unggulan LPDP', 'Wajib punya LoA unconditional', 'Cek status di daftar tahun berjalan'] },
      { slug: 'comm-melbourne', n: 'MA Communication', kmp: 'University of Melbourne', bid: 'km', dur: '2 tahun', bhs: 'Inggris', d: 'Termasuk kampus yang sering muncul di daftar LPDP. Perlu diingat bahwa alokasi kuota 2026 condong ke STEM, jadi persaingan di bidang sosial jadi lebih ketat.', p: ['Sering muncul di daftar tujuan LPDP', 'Persaingan lebih ketat karena kuota condong ke STEM', 'Wajib punya LoA unconditional'] },
    ],
  },
  {
    slug: 'lpdp-akselerasi-magister', k: 'LPDP Akselerasi Magister', ng: 'Lintas negara', b: 'semua',
    bid: ['si', 'ti', 'ar', 'hi', 'km'], loa: 0, kerja: 0, ikat: 1, td: '30 April', st: 'tutup', u: 'lpdp.kemenkeu.go.id',
    intro: 'Buat mahasiswa S1 yang masih aktif, supaya bisa langsung lanjut magister tanpa jeda. Tapi cuma berlaku di pasangan kampus tertentu yang sudah bekerja sama.',
    fk: [['Sasaran', 'Mahasiswa S1 aktif'], ['Pendanaan', 'Maksimal 24 bulan'], ['Kampus', 'Pasangan tertentu'], ['Skema', 'Terintegrasi']],
    ceklis: [[1, 'Berstatus mahasiswa S1 aktif', ''], [1, 'Kampus asal termasuk mitra program', 'Nggak berlaku untuk semua kampus'], [0, 'Cek pasangan kampus tujuan', 'Misalnya Wisconsin-Madison dan Georgetown SFS'], [0, 'Rencana studi terintegrasi', ''], [0, 'Esai komitmen kontribusi', '']],
    waktu: [['2 April', 'Pendaftaran dibuka', 0], ['30 April', 'Pendaftaran ditutup', 0], ['Mei sampai Juni', 'Seleksi', 0]],
    awas: 'Skema ini terikat pada pasangan kampus asal dan kampus tujuan yang sudah bekerja sama. Kalau kampus S1 kamu nggak termasuk, jalur ini tertutup terlepas dari sebagus apa pun profil kamu.',
    pcat: 'Cuma berlaku di pasangan kampus tertentu. Ini contoh kampus tujuan yang disebut LPDP.',
    prog: [
      { slug: 'cs-wisconsin', n: 'MS Computer Sciences', kmp: 'University of Wisconsin-Madison', bid: 'ti', dur: 'Bagian dari 24 bulan', bhs: 'Inggris', d: 'Salah satu kampus tujuan yang disebut langsung dalam skema ini. Program ilmu komputernya punya sejarah panjang di sistem basis data.', p: ['Disebut langsung sebagai kampus tujuan skema', 'Kuat di sistem basis data', 'Bagian dari paket 24 bulan'] },
      { slug: 'sfs-georgetown', n: 'MA Foreign Service', kmp: 'Georgetown University SFS', bid: 'hi', dur: 'Bagian dari 24 bulan', bhs: 'Inggris', d: 'School of Foreign Service Georgetown adalah salah satu sekolah diplomasi tertua di AS, berada di Washington DC dekat pusat kebijakan luar negeri.', p: ['Sekolah diplomasi tertua di AS', 'Lokasi di Washington DC', 'Disebut langsung dalam skema'] },
    ],
  },
];

export function cariBeasiswa(slug) {
  return BEASISWA.find((d) => d.slug === slug) || null;
}

export function cariProgram(slugBeasiswa, slugProgram) {
  const b = cariBeasiswa(slugBeasiswa);
  if (!b) return { beasiswa: null, program: null };
  return { beasiswa: b, program: b.prog.find((p) => p.slug === slugProgram) || null };
}

export function saring(jwb) {
  return BEASISWA.filter((d) => {
    if (jwb.bidang && !d.bid.includes(jwb.bidang)) return false;
    if (jwb.benua !== 'semua' && d.b !== 'semua' && d.b !== jwb.benua) return false;
    if (jwb.loa === 'belum' && d.loa) return false;
    if (jwb.kerja === '0' && d.kerja > 0) return false;
    if (jwb.ikat === 'tolak' && d.ikat) return false;
    return true;
  }).sort((a, b) => URUT[a.st] - URUT[b.st]);
}

export const TOTAL_PROGRAM = BEASISWA.reduce((n, d) => n + d.prog.length, 0);
